# Generated by Django 4.1.4 on 2023-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_reviewcomment_report_bills_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
