# Generated by Django 4.1.4 on 2022-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childcaretitle', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.FileField(blank=True, upload_to='childcare_image')),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.FileField(blank=True, upload_to='package_image')),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
